### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by firstnecron** [firstnecron/tt-omdb-movie-search-app#1]
**Request Data**
- [ ] Search form sends data request to API based on the value of the search field.
- [ ] 's' parameter is used to return movie data
- [ ] (Extra) The provided 'year' field to filter search by year of release is used by adding the 'y' parameter to the API call

**Displaying Items from API**
- [ ] App displays movie titles, years of release, and poster images inside list items within the #movies
- [ ] Provided CSS class names are used and the page displays as shown in example images.
- [ ] (Extra) Movies click to or load a description page displaying title, year, poster, plot information, and IMDb rating.
- [ ] (Extra) Movie title on the description page links to the movie's IMDb page.
- [ ] (Extra) The page roughly matches the description-page.png mockup provided in the examples folder of the project files

**Displaying poster images**
- [ ] App displays the provided placeholder icon if "Poster" parameter returns at "N/A"
- [ ] Page displays "No movies found that match: 'title'." when search form returns no movies
